# Generated by Django 3.2.7 on 2021-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=123, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=123, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=260, null=True)),
            ],
        ),
    ]
