# Generated by Django 3.2.7 on 2021-09-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverify',
            name='username',
        ),
    ]
