# Generated by Django 3.2.7 on 2021-09-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_emailverify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
